# 🧠 ConfLab Dataset Preprocessing: JSON to DataFrame

This notebook parses raw ConfLab skeleton annotation JSON files into a structured `pandas.DataFrame`. Each row corresponds to an individual agent's keypoints and occlusion status in a given frame. The resulting DataFrame can be used for downstream analysis such as visibility scoring, camera selection, and sliding window feature extraction.

**Contents:**
- Load and parse JSON annotation files
- Extract keypoints and occlusion masks
- Structure data per video, camera, frame, and agent

In [2]:
#imports
import numpy as np
import pandas as pd
import json
import os
from tqdm import tqdm

In [18]:
def parse_conflab_skeleton_json(data, video_id, camera_id):
    """
    Parses ConfLab skeleton annotation JSON into a structured DataFrame.

    Args:
        json_data (dict): Parsed JSON object from a ConfLab annotation file.
        video_id (str or int): Identifier for the video session.
        camera_id (str or int): Identifier for the camera.

    Returns:
        pd.DataFrame: Each row is a single agent-frame observation.
                      Columns: video_id, camera_id, frame_id, agent_id, keypoints (Nx2), occluded (N,)
    """

    rows = []
    skeletons_by_frame = data["annotations"]["skeletons"]
    for frame_index, frame_skeletons in tqdm(enumerate(skeletons_by_frame), desc=f"Parsing skeleton annotations for {video_id}_{camera_id}"):
        for agent_id_str, skeleton_data in frame_skeletons.items():
            agent_id = int(agent_id_str)
            num_kp = skeleton_data["num_keypoints"]
            keypoints = np.array(skeleton_data["keypoints"]).reshape(-1, 2)
            occluded = np.array(skeleton_data["occluded"])
            frame_id = frame_index

            rows.append({
                "video_id": video_id,
                "camera_id": camera_id,
                "frame_id": frame_id,
                "agent_id": agent_id,
                "num_kp": num_kp,
                "keypoints": keypoints,
                "occluded": occluded
            })
    return pd.DataFrame(rows)

In [19]:
def extract_ids_from_filename(filename):
    base = os.path.basename(filename).replace(".json", "")
    parts = base.split("_")
    video_id = parts[1] + "_" + parts[2]  # e.g., "conf01"
    camera_id = parts[0]
    return video_id, camera_id

def parse_all_jsons_in_folder(folder_path):
    all_dfs = []
    for f_id, file in enumerate (os.listdir(folder_path)):
        print(f"Parsing {file}; {f_id}/32")
        if file.endswith(".json"):
            json_path = os.path.join(folder_path, file)
            with open(json_path) as f:
                data = json.load(f)

            video_id, camera_id = extract_ids_from_filename(file)
            df = parse_conflab_skeleton_json(data, video_id, camera_id)
            all_dfs.append(df)

    full_df = pd.concat(all_dfs, ignore_index=True)
    return full_df

In [20]:

folder = "W:\\staff-bulk\\ewi\\insy\\SPCDataSets\\conflab-mm\\v4\\release\\annotations\\pose\\coco"
df = parse_all_jsons_in_folder(folder)
df.to_pickle("dataframes\\conflab_skeleton_data.pkl")
print(f"✅ Done! Parsed {len(df)} rows and saved to conflab_skeleton_data.pkl")

Parsing cam2_vid2_seg8_coco.json; 0/32

Parsing skeleton annotations for vid2_seg8_cam2: 7194it [00:00, 217828.51it/s]

Parsing cam2_vid2_seg9_coco.json; 1/32

Parsing skeleton annotations for vid2_seg9_cam2: 5879it [00:00, 9332.90it/s]

Parsing cam2_vid3_seg1_coco.json; 2/32

Parsing skeleton annotations for vid3_seg1_cam2: 7195it [00:00, 11901.89it/s]

Parsing cam2_vid3_seg2_coco.json; 3/32

Parsing skeleton annotations for vid3_seg2_cam2: 7194it [00:00, 14108.38it/s]

Parsing cam2_vid3_seg3_coco.json; 4/32

Parsing skeleton annotations for vid3_seg3_cam2: 7194it [00:00, 11922.78it/s]

Parsing cam2_vid3_seg4_coco.json; 5/32

Parsing skeleton annotations for vid3_seg4_cam2: 7195it [00:00, 14967.76it/s]

Parsing cam2_vid3_seg5_coco.json; 6/32

Parsing skeleton annotations for vid3_seg5_cam2: 7195it [00:00, 12579.49it/s]

Parsing cam2_vid3_seg6_coco.json; 7/32

Parsing skeleton annotations for vid3_seg6_cam2: 7194it [00:00, 14087.50it/s]

Parsing cam4_vid2_seg8_coco.json; 8/32

Parsing skeleton annotations for vid2_seg8_cam4: 7194it [00:00, 8157.42it/s]

Parsing cam4_vid2_seg9_coco.json; 9/32

Parsing skeleton annotations for vid2_seg9_cam4: 5879it [00:01, 5295.58it/s]

Parsing cam4_vid3_seg1_coco.json; 10/32

Parsing skeleton annotations for vid3_seg1_cam4: 7194it [00:09, 767.69it/s]

Parsing cam4_vid3_seg2_coco.json; 11/32

Parsing skeleton annotations for vid3_seg2_cam4: 7195it [00:01, 7085.17it/s]

Parsing cam4_vid3_seg3_coco.json; 12/32

Parsing skeleton annotations for vid3_seg3_cam4: 7194it [00:01, 4483.78it/s]

Parsing cam4_vid3_seg4_coco.json; 13/32

Parsing skeleton annotations for vid3_seg4_cam4: 7195it [00:01, 4982.38it/s]

Parsing cam4_vid3_seg5_coco.json; 14/32

Parsing skeleton annotations for vid3_seg5_cam4: 7195it [00:01, 5239.96it/s]

Parsing cam4_vid3_seg6_coco.json; 15/32

Parsing skeleton annotations for vid3_seg6_cam4: 7194it [00:01, 6201.61it/s]

Parsing cam6_vid2_seg8_coco.json; 16/32

Parsing skeleton annotations for vid2_seg8_cam6: 7194it [00:01, 5193.73it/s]

Parsing cam6_vid2_seg9_coco.json; 17/32

Parsing skeleton annotations for vid2_seg9_cam6: 5879it [00:01, 5878.45it/s]

Parsing cam6_vid3_seg1_coco.json; 18/32

Parsing skeleton annotations for vid3_seg1_cam6: 7194it [00:01, 6690.97it/s]

Parsing cam6_vid3_seg2_coco.json; 19/32

Parsing skeleton annotations for vid3_seg2_cam6: 7194it [00:01, 6496.76it/s]

Parsing cam6_vid3_seg3_coco.json; 20/32

Parsing skeleton annotations for vid3_seg3_cam6: 7194it [00:01, 5111.56it/s]

Parsing cam6_vid3_seg4_coco.json; 21/32

Parsing skeleton annotations for vid3_seg4_cam6: 7195it [00:00, 11284.56it/s]

Parsing cam6_vid3_seg5_coco.json; 22/32

Parsing skeleton annotations for vid3_seg5_cam6: 7197it [00:05, 1436.32it/s]

Parsing cam6_vid3_seg6_coco.json; 23/32

Parsing skeleton annotations for vid3_seg6_cam6: 7196it [00:00, 8357.19it/s]

Parsing cam8_vid2_seg8_coco.json; 24/32

Parsing skeleton annotations for vid2_seg8_cam8: 7194it [00:00, 23071.81it/s]

Parsing cam8_vid2_seg9_coco.json; 25/32

Parsing skeleton annotations for vid2_seg9_cam8: 5879it [00:00, 12832.72it/s]

Parsing cam8_vid3_seg1_coco.json; 26/32

Parsing skeleton annotations for vid3_seg1_cam8: 7194it [00:00, 18281.15it/s]

Parsing cam8_vid3_seg2_coco.json; 27/32

Parsing skeleton annotations for vid3_seg2_cam8: 7194it [00:00, 15285.97it/s]

Parsing cam8_vid3_seg3_coco.json; 28/32

Parsing skeleton annotations for vid3_seg3_cam8: 7194it [00:00, 10149.95it/s]

Parsing cam8_vid3_seg4_coco.json; 29/32

Parsing skeleton annotations for vid3_seg4_cam8: 7195it [00:00, 13867.59it/s]

Parsing cam8_vid3_seg5_coco.json; 30/32

Parsing skeleton annotations for vid3_seg5_cam8: 7195it [00:00, 13483.34it/s]

Parsing cam8_vid3_seg6_coco.json; 31/32

Parsing skeleton annotations for vid3_seg6_cam8: 7195it [00:00, 13518.22it/s]

✅ Done! Parsed 3926964 rows and saved to conflab_skeleton_data.pkl

## 😂 Adding Laughter Annotations to Agents per Frame

The following code blocks enrich our existing pose-tracking DataFrame by incorporating **laughter annotations**.
### What This Will Do:
- Load or read external laughter annotation files for each modality.
- Align annotations with the agent and frame IDs already present in the pose DataFrame.
- Add new columns for each modality with binary label for each `(agent_id, frame_id)` pair.

In [3]:
def csv_to_pd(folder_name, file, index):
    full_path = os.path.join(folder_name, file)
    fp_a = full_path + f"_ann{index}.csv"
    df = pd.read_csv(fp_a)
    df = df.rename(columns={col: f"agent {col} ann{index}" for col in df.columns})
    return df

def generate_big_annotations(folder_name, file):
    csv_1 = csv_to_pd(folder_name, file, 1)
    csv_2 = csv_to_pd(folder_name, file, 2)
    csv_3 = csv_to_pd(folder_name, file, 3)

    agents_1 = [col.split()[1] for col in csv_1.columns]
    agents_2 = [col.split()[1] for col in csv_2.columns]
    agents_3 = [col.split()[1] for col in csv_3.columns]
    all_agents = sorted(set(agents_1) | set(agents_2) | set(agents_3), key=int)

    for agent in all_agents:
        csv_1[f"agent {agent} ann1"] = csv_1.get(f"agent {agent} ann1", None)
        csv_2[f"agent {agent} ann2"] = csv_2.get(f"agent {agent} ann2", None)
        csv_3[f"agent {agent} ann3"] = csv_3.get(f"agent {agent} ann3", None)

# Ensure consistent column order
    csv_1 = csv_1.sort_index(axis=1)
    csv_2 = csv_2.sort_index(axis=1)
    csv_3 = csv_3.sort_index(axis=1)


    interleaved_cols = [
    f"agent {agent} ann{i}"
    for agent in all_agents
    for i in range(1, 4)  # ann1, ann2, ann3
    ]


    combined_df = pd.concat([csv_1, csv_2, csv_3], axis=1)
    combined_df["frame_id"] = combined_df.index
    combined_df["video_id"] = file
    combined_df = combined_df[["frame_id", "video_id"] + interleaved_cols]


    return combined_df

def gen_pd_for_modality(folder_name, test_videos = None):
    if test_videos is None:
        pose_annotated_segments = ["vid2_seg8", "vid2_seg9", "vid3_seg1", "vid3_seg2", "vid3_seg3", "vid3_seg4", "vid3_seg5", "vid3_seg6"]
    else:
        pose_annotated_segments = test_videos
    al_dfs = []
    for file in pose_annotated_segments:
       df = generate_big_annotations(folder_name, file)
       al_dfs.append(df)
    full_df = pd.concat(al_dfs, ignore_index=True)
    return full_df

In [4]:
folder_laughing_no_audio = "W:\\staff-bulk\\ewi\\insy\\SPCDataSets\\conflab-mm\\v4\\release\\annotations\\actions\\laughing\\No_Audio"
folder_laughing_only_audio = "W:\\staff-bulk\\ewi\\insy\\SPCDataSets\\conflab-mm\\v4\\release\\annotations\\actions\\laughing\\Only_audio"
folder_laughing_with_audio = "W:\\staff-bulk\\ewi\\insy\\SPCDataSets\\conflab-mm\\v4\\release\\annotations\\actions\\laughing\\With_audio"

df_no_audio = gen_pd_for_modality(folder_laughing_no_audio)
df_only_audio = gen_pd_for_modality(folder_laughing_only_audio)
df_with_audio = gen_pd_for_modality(folder_laughing_with_audio)

df_no_audio.to_pickle("laugh_annotation_no_audio.pkl")
df_with_audio.to_pickle("laugh_annotation_with_audio.pkl")
df_only_audio.to_pickle("laugh_annotation_only_audio.pkl")

C:\Users\Vassil.Guenov\AppData\Local\Temp\ipykernel_31420\3566726776.py:53: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full_df = pd.concat(al_dfs, ignore_index=True)
C:\Users\Vassil.Guenov\AppData\Local\Temp\ipykernel_31420\3566726776.py:38: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  combined_df["video_id"] = file
C:\Users\Vassil.Guenov\AppData\Local\Temp\ipykernel_31420\3566726776.py:53: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full_df = pd.concat(al_dfs, ignore_index=True)
C:\Users\Vassil.Guenov\AppData\Local\Temp\ipykernel_31420\3566726776.py:53: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full_df = pd.concat(al_dfs, ignore_index=True)

In [5]:
pd.set_option('display.max_columns', None)

# Optional: Also show full contents in each cell
pd.set_option('display.max_colwidth', None)
display(df_no_audio)

,frame_id,video_id,agent 1 ann1,agent 1 ann2,agent 1 ann3,agent 2 ann1,agent 2 ann2,agent 2 ann3,agent 3 ann1,agent 3 ann2,agent 3 ann3,agent 4 ann1,agent 4 ann2,agent 4 ann3,agent 5 ann1,agent 5 ann2,agent 5 ann3,agent 6 ann1,agent 6 ann2,agent 6 ann3,agent 7 ann1,agent 7 ann2,agent 7 ann3,agent 8 ann1,agent 8 ann2,agent 8 ann3,agent 9 ann1,agent 9 ann2,agent 9 ann3,agent 10 ann1,agent 10 ann2,agent 10 ann3,agent 11 ann1,agent 11 ann2,agent 11 ann3,agent 12 ann1,agent 12 ann2,agent 12 ann3,agent 13 ann1,agent 13 ann2,agent 13 ann3,agent 14 ann1,agent 14 ann2,agent 14 ann3,agent 15 ann1,agent 15 ann2,agent 15 ann3,agent 16 ann1,agent 16 ann2,agent 16 ann3,agent 17 ann1,agent 17 ann2,agent 17 ann3,agent 18 ann1,agent 18 ann2,agent 18 ann3,agent 19 ann1,agent 19 ann2,agent 19 ann3,agent 20 ann1,agent 20 ann2,agent 20 ann3,agent 21 ann1,agent 21 ann2,agent 21 ann3,agent 22 ann1,agent 22 ann2,agent 22 ann3,agent 23 ann1,agent 23 ann2,agent 23 ann3,agent 24 ann1,agent 24 ann2,agent 24 ann3,agent 25 ann1,agent 25 ann2,agent 25 ann3,agent 26 ann1,agent 26 ann2,agent 26 ann3,agent 27 ann1,agent 27 ann2,agent 27 ann3,agent 28 ann1,agent 28 ann2,agent 28 ann3,agent 29 ann1,agent 29 ann2,agent 29 ann3,agent 30 ann1,agent 30 ann2,agent 30 ann3,agent 31 ann1,agent 31 ann2,agent 31 ann3,agent 32 ann1,agent 32 ann2,agent 32 ann3,agent 33 ann1,agent 33 ann2,agent 33 ann3,agent 34 ann1,agent 34 ann2,agent 34 ann3,agent 35 ann1,agent 35 ann2,agent 35 ann3,agent 44 ann1,agent 44 ann2,agent 44 ann3,agent 48 ann1,agent 48 ann2,agent 48 ann3,agent 36 ann1,agent 36 ann2,agent 36 ann3,agent 37 ann1,agent 37 ann2,agent 37 ann3,agent 40 ann1,agent 40 ann2,agent 40 ann3,agent 41 ann1,agent 41 ann2,agent 41 ann3,agent 42 ann1,agent 42 ann2,agent 42 ann3,agent 43 ann1,agent 43 ann2,agent 43 ann3,agent 50 ann1,agent 50 ann2,agent 50 ann3,agent 45 ann1,agent 45 ann2,agent 45 ann3,agent 46 ann1,agent 46 ann2,agent 46 ann3,agent 47 ann1,agent 47 ann2,agent 47 ann3
0,0,vid2_seg8,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,vid2_seg8,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,vid2_seg8,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,vid2_seg8,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,vid2_seg8,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56284,7196,vid3_seg6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,None
56285,7197,vid3_seg6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,None
56286,7198,vid3_seg6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,None
56287,7199,vid3_seg6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,None
56288,7200,vid3_seg6,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,None

## Combining the dataframes together
Make so there is one dataframe with all the data:
- Pose estimation coordinates
- Laughter indication for each modality (majority rule)

In [6]:
df = pd.read_pickle("dataframes\\conflab_skeleton_data.pkl")

In [7]:
def majority_vote(vals):
    filtered = [v for v in vals if pd.notna(v)]
    if not filtered:
        return None
    return max(set(filtered), key=filtered.count)

def assign_majority_annotations(pose_df, ann_df, modality):
    # Make sure merge keys are aligned
    key_cols = ["video_id", "frame_id"]
    ann_df = ann_df.set_index(key_cols)
    agents_ids = []
    cams_ids = []
    video_ids = []
    nums = []

    results = []
    for i, row in pose_df.iterrows():
        video_id = row["video_id"]
        frame_id = row["frame_id"]
        agent_id = row["agent_id"]
        camera_id = row["camera_id"]

        try:
            ann_row = ann_df.loc[(video_id, frame_id)]
        except KeyError:
            results.append(None)
            continue

        agent_cols = [col for col in ann_row.index if col.startswith(f"agent {agent_id} ann")]
        agent_votes = [ann_row[col] for col in agent_cols if col in ann_row]

        final_vote = majority_vote(agent_votes)
        if final_vote is None:
            agents_ids.append(agent_id)
            cams_ids.append(camera_id)
            video_ids.append(video_id)
            nums.append(i)
        results.append(final_vote)
    pose_df[f"is_laughing_{modality}"] = results
    print(f"{modality} nan: {pose_df[f'is_laughing_{modality}'].isna().sum()}")
    print(f"Agent IDs: {np.unique(agents_ids)}")
    print(f"Video IDs: {np.unique(video_ids)}")
    print(f"Camera IDs: {np.unique(cams_ids)}")
    return pose_df, nums

In [8]:
final_df_na,frames = assign_majority_annotations(df, df_no_audio, "no_audio")
final_df_oa,frames = assign_majority_annotations(final_df_na, df_only_audio, "only_audio")
final_df_wa,frames = assign_majority_annotations(final_df_oa, df_with_audio, "with_audio")
display(final_df_wa)

no_audio nan: 0
Agent IDs: []
Video IDs: []
Camera IDs: []
only_audio nan: 0
Agent IDs: []
Video IDs: []
Camera IDs: []
with_audio nan: 7197
Agent IDs: [14]
Video IDs: ['vid3_seg5']
Camera IDs: ['cam6']

,video_id,camera_id,frame_id,agent_id,num_kp,keypoints,occluded,is_laughing_no_audio,is_laughing_only_audio,is_laughing_with_audio
0,vid2_seg8,cam2,0,26,1,"[[0.8255949020030402, 0.477211178191941], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None]]","[0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]",0.0,0.0,0.0
1,vid2_seg8,cam2,1,26,1,"[[0.8255949020030402, 0.477211178191941], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None]]","[0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]",0.0,0.0,0.0
2,vid2_seg8,cam2,2,26,1,"[[0.8255949020030402, 0.477211178191941], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None]]","[0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]",0.0,0.0,0.0
3,vid2_seg8,cam2,3,26,1,"[[0.8255949020030402, 0.477211178191941], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None]]","[0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]",0.0,0.0,0.0
4,vid2_seg8,cam2,4,26,1,"[[0.8255949020030402, 0.477211178191941], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None]]","[0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]",0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
3926959,vid3_seg6,cam8,7194,10,1,"[[None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [0.8173452988316031, 0.9352436565511089], [None, None], [None, None], [None, None], [None, None]]","[None, None, None, None, None, None, None, None, None, None, None, None, 0, None, None, None, None]",0.0,0.0,0.0
3926960,vid3_seg6,cam8,7194,2,1,"[[None, None], [None, None], [None, None], [None, None], [0.5362242061434043, 0.8968862568855628], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None]]","[None, None, None, None, 0, None, None, None, None, None, None, None, None, None, None, None, None]",0.0,0.0,0.0
3926961,vid3_seg6,cam8,7194,11,1,"[[None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [0.2976202990310729, 0.8923736216307927], [None, None], [None, None]]","[None, None, None, None, None, None, None, None, None, None, None, None, None, None, 0, None, None]",0.0,0.0,0.0
3926962,vid3_seg6,cam8,7194,17,1,"[[None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [0.42517185575867555, 0.97585737384404], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None]]","[None, None, None, None, None, None, 1, None, None, None, None, None, None, None, None, None, None]",0.0,0.0,0.0
3926963,vid3_seg6,cam8,7194,22,2,"[[None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [0.1212057081341896, 0.9138086390909508], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [0.20877841872328995, 0.8179151399270855]]","[None, None, None, None, None, None, None, None, None, 0, None, None, None, None, None, None, 1]",0.0,0.0,0.0

In [44]:
pd.set_option('display.max_rows', 1000)
print(final_df.columns)
print(final_df[
    (final_df['camera_id'] == 'cam8')
    & (final_df['video_id'] == 'vid3_seg5')
])

Index(['video_id', 'camera_id', 'frame_id', 'agent_id', 'num_kp', 'keypoints',
       'occluded', 'is_laughing_no_audio', 'is_laughing_only_audio',
       'is_laughing_with_audio'],
      dtype='object')
          video_id camera_id  frame_id  agent_id  num_kp  \
3739901  vid3_seg5      cam8         0        31      17
3739902  vid3_seg5      cam8         0        10      17
3739903  vid3_seg5      cam8         0        35      17
3739904  vid3_seg5      cam8         0         2      20
3739905  vid3_seg5      cam8         0        17      17
...            ...       ...       ...       ...     ...
3833431  vid3_seg5      cam8      7194        11      17
3833432  vid3_seg5      cam8      7194        22      17
3833433  vid3_seg5      cam8      7194        45      18
3833434  vid3_seg5      cam8      7194        40      17
3833435  vid3_seg5      cam8      7194         5      17

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            keypoints  \
3739901               [[0.5349550364247216, 0.17260829849495737], [0.5349550364247216, 0.22788808036589142], [0.5533579973456195, 0.19404331595511548], [0.5051295480356802, 0.20081226883727066], [0.4879957568334649, 0.25045125663974205], [0.4975145297235845, 0.3000902444422135], [0.5641459399544217, 0.1805054101908051], [0.5793759765786131, 0.2369133508754317], [0.5711263734071761, 0.28542417986421054], [0.5222633392378955, 0.3091155149517537], [0.5235325089565781, 0.3147563090202164], [0.5267054332532847, 0.318140785461294], [0.5476467336115478, 0.3057310385106761], [0.5495504881895716, 0.320397103088679], [0.5044949631763389, 0.31362815020652385], [0.5235325089565781, 0.3440884381762222], [0.5152829057851411, 0.3147563090202164]]
3739902                            [[0.9131676125921405, 0.7581227228013814], [0.885245878781123, 0.7694043109383067], [0.89349548195256, 0.7050992585578324], [0.8655737481415425, 0.6768952882155191], [0.8141723745348967, 0.674638970588134], [0.8255949020030402, 0.7423284994096859], [0.9233209703416014, 0.7197653231358353], [0.89349548195256, 0.7513537699192262], [0.860497069266812, 0.7795577402615395], [0.8109994502381901, 0.6847923999113669], [0.7830777164271726, 0.672382652960749], [0.7564251523348378, 0.6295126180404328], [0.8313061657371119, 0.7017147821167548], [0.8052881865041184, 0.7152526878810652], [0.8008460924887292, 0.6735108117744415], [0.7399259459919637, 0.6633573824512087], [0.7767318678337596, 0.7073555761852175]]
3739903                   [[0.612374389264361, 0.45916063717286043], [0.5876255797500501, 0.44900720784962767], [0.5996826920775349, 0.5020306720931766], [0.6180856529984329, 0.44111009615377994], [0.5800105614379544, 0.407265331743004], [0.5597038459390326, 0.4715703841234783], [0.5869909948907088, 0.5031588309068692], [0.5476467336115478, 0.5054151485342543], [0.5762030522819066, 0.44900720784962767], [0.5692226188291521, 0.4681859076824007], [0.5692226188291521, 0.4681859076824007], [0.5787413917192719, 0.4941335603973289], [0.5590692610796913, 0.5212093719259497], [0.55843467622035, 0.5234656895533347], [0.5647805248137631, 0.5426443893861078], [0.5628767702357391, 0.46592959005501566], [0.5432046395961586, 0.5268501659944124]]
3739904                       [[0.5228979240972368, 0.9950360736768131], [0.5209941695192128, 0.992779756049428], [0.5241670938159194, 0.9950360736768131], [0.5070333026137042, 0.9826263267261952], [0.49687994486424325, 0.8912454628171002], [0.48926492655214754, 0.920577591973106], [0.5432046395961586, 0.9950360736768131], [0.5489159033302304, 0.9769855326577326], [0.550185073048913, 0.9871389619809654], [0.5083024723323868, 0.920577591973106], [0.4841882476774171, 0.8912454628171002], [0.494341605426878, 0.8359656809461661], [0.535589621284063, 0.9296028624826462], [0.5222633392378955, 0.8878609863760225], [0.5228979240972368, 0.8551443807789392], [0.47340030506861486, 0.8438627926420138], [0.5184558300818477, 0.8754512394254047]]
3739905                      [[0.3731358972926884, 0.992779756049428], [0.3731358972926884, 0.992779756049428], [0.3737704821520297, 0.992779756049428], [0.35980961524652094, 0.9950360736768131], [0.3648862941212514, 0.9781136914714251], [0.3629825395432275, 0.9781136914714251], [0.3845584247608319, 0.9882671207946578], [0.3978847068069994, 0.9138086390909508], [0.3648862941212514, 0.9566786740112669], [0.37948174588610145, 0.939756291805879], [0.382654670182808, 0.9262183860415686], [0.390904273354245, 0.8980144156992553], [0.40549972511909504, 0.9160649567183359], [0.41438391314987333, 0.884476509934945], [0.41565308286855596, 0.8393501573872437], [0.39598095222897545, 0.920577591973106], [0.4365943832268191, 0.8585288572200167]]
...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ...
3833431        [[0.15737704511664408, 0.9950360736768131], [0.16054996941335062, 0.992779756049428], [0.15420412081993756, 0.9905234384220429], [0.15610787539796148, 0.9781136914714251], [0.19227921238041595, 0.8991425745129479], [0.1865679486463442, 0.8968862568855628], [0.19481755181778118, 0.9961642324905056], [0.23352722823760091, 0.9961642324905056], [0.23352722823760091, 0.9905234384220429], [0.22781596450352914, 0.9081678450224882], [0.24939184972113357, 0.8743230806117122], [0.27667899867280976, 0.833709363318781], [0.23860390711233137, 0.9702165797755774], [0.26398730148598365, 0.9442689270606491], [0.2900052807189772, 0.9171931155320284], [0.2525647740178401, 0.8325812045050884], [0.27350607437610325, 0.9442689270606491]]
3833432  [[0.012691697186826136, 0.992779756049428], [0.008884188030778296, 0.9950360736768131], [0.014595451764850057, 0.9939079148631206], [0.0012691697186826135, 0.9950360736768131], [0.04569010987257409, 0.9984205501178907], [0.12374404757155483, 0.9171931155320284], [0.03934426127916102, 0.9634476268934222], [0.103437332072633, 0.9126804802772582], [0.07995769227700465, 0.9905234384220429], [0.10026440777592648, 0.8991425745129479], [0.14341617821113534, 0.9002707333266404], [0.16499206342873976, 0.8754512394254047], [0.12310946271221351, 0.9081678450224882], [0.1567424602573028, 0.8517599043378615], [0.18149126977161376, 0.8280685692503184], [0.17260708174083544, 0.8935017804444852], [0.19799047611448772, 0.8303248868777034]]
3833433                   [[0.44167106210154955, 0.5934115360022717], [0.4581702684444235, 0.5595667715914958], [0.43532521350813647, 0.5584386127778033], [0.4683236261938844, 0.636281570922588], [0.5032257934576563, 0.6249999827856626], [0.5286091878313086, 0.6013086476981194], [0.4270756103366995, 0.5561822951504182], [0.44167106210154955, 0.5223375307396423], [0.4499206652729865, 0.515568577857487], [0.4746694747872975, 0.585514424306424], [0.47276572020927354, 0.5877707419338091], [0.47149655049059097, 0.583258106679039], [0.4746694747872975, 0.5437725481998004], [0.48101532338071057, 0.5347472776902601], [0.4854574173960997, 0.515568577857487], [0.48101532338071057, 0.5821299478653464], [0.5000528691609497, 0.513312260230102]]
3833434            [[0.6237969167325046, 0.11958483425140837], [0.6136435589830437, 0.16132671035803206], [0.6098360498269958, 0.12522562831987102], [0.6034902012335828, 0.10379061085971293], [0.6047593709522654, 0.06430505238047432], [0.5946060132028045, 0.11507219899663824], [0.647276556528133, 0.17260829849495737], [0.6606028385743004, 0.21435017460158104], [0.6276044258885525, 0.24932309782604953], [0.581279731156637, 0.22788808036589142], [0.5781068068599305, 0.24706678019866446], [0.5730301279852, 0.2594765271492823], [0.6072977103896307, 0.25383573308081964], [0.6066631255302893, 0.2662454800314375], [0.597778937499511, 0.27865522698205536], [0.5622421853763978, 0.2809115446094404], [0.5971443526401697, 0.30234656206959853]]
3833435                      [[0.6637757628710069, 0.9893952796083504], [0.668217856886396, 0.9972923913041981], [0.6796403843545396, 0.9961642324905056], [0.6314119350446002, 0.9893952796083504], [0.6149127287017263, 0.9961642324905056], [0.6149127287017263, 0.9984205501178907], [0.6942358361193897, 0.9860108031672729], [0.7158117213369941, 0.9984205501178907], [0.7208884002117245, 0.9961642324905056], [0.6441036322314264, 0.9984205501178907], [0.6967741755567549, 0.9961642324905056], [0.6320465199039416, 0.9961642324905056], [0.6720253660424439, 0.9972923913041981], [0.659968253714959, 0.9961642324905056], [0.6567953294182526, 0.9882671207946578], [0.6739291206204678, 0.9611913092660371], [0.6574299142775939, 0.9950360736768131]]

                                                    occluded  \
3739901  [0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1]
3739902  [0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1]
3739903  [0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0]
3739904  [1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1]
3739905  [1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0]
...                                                      ...
3833431  [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1]
3833432  [1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
3833433  [0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1]
3833434  [0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0]
3833435  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1]

         is_laughing_no_audio  is_laughing_only_audio  is_laughing_with_audio
3739901                   0.0                     0.0                     0.0
3739902                   0.0                     0.0                     0.0
3739903                   0.0                     0.0                     0.0
3739904                   0.0                     0.0                     0.0
3739905                   0.0                     0.0                     0.0
...                       ...                     ...                     ...
3833431                   0.0                     1.0                     0.0
3833432                   0.0                     0.0                     0.0
3833433                   0.0                     0.0                     1.0
3833434                   0.0                     0.0                     0.0
3833435                   0.0                     0.0                     0.0

[93535 rows x 10 columns]

In [ ]:
test_df, frames = assign_majority_annotations(final_df_oa, df_with_audio, "with_audio")
# rows_with_nans = [2894899, 2894924, 2894949, 2894974, 2894999]  # etc.
# print(final_df_wa.loc[rows_with_nans])

In [9]:
final_df_wa.to_pickle("dataframes\\final_df.pkl")